### ISSUE TITLE
Add text to the survey form that explains whether route_id and stop_id lists are unions or intersections

### ISSUE THREAD

**Issue by aaronbrethorst** [OneBusAway/onebusaway-deep-links#176]
From our conversation with Devin Braun

## User story

as a transit agency employee that is creating a new survey,
I want to understand if constraining by stop_ids and route_ids are 'union' or 'intersection' operations,
so that I can understand where my survey will appear

## Acceptance criteria

Correct me if I am wrong, but the lists of routes and stops are _union_ operations, right? in other words, if I specify that a survey should show up on Stop 1 and Route A, it will show up on both, right?

If so, this should really be as simple as adding a line of text to the survey form that says something like "If the route and stop lists are blank, this survey will show up everywhere. If you specify any routes or stops, it will up on all routes and stops specified."

**Comment by amrhossamdev** [comment]
Yes if we have `route A` that contains `stop B` and you added `stop B` in the stop list and also added `route A` to the route list it will appear in both... by adding `route A` you add all the stops with-in the route.

If you removed the `stop B` from the stop list the survey will still be visible because `route A` contains the `stop B`
